### ISSUE TITLE
Invalid JSON on initialize

### ISSUE THREAD

**Issue by hurricaneMitch** [tim-hellhake/azure-iot-bridge#1]
Followed directions in README. Logs show this error
`
2019-10-03 03:25:33.870 INFO   : Unloading AzureIotBridge

2019-10-03 03:25:33.878 INFO   : azure-iot-bridge: Adapter: AzureIotBridge unloaded

2019-10-03 03:25:45.283 INFO   : Loading add-on: azure-iot-bridge

2019-10-03 03:25:46.064 INFO   : azure-iot-bridge: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3

2019-10-03 03:25:46.106 INFO   : azure-iot-bridge: Loading add-on for azure-iot-bridge from /home/pi/.mozilla-iot/addons/azure-iot-bridge

2019-10-03 03:25:47.305 INFO   : azure-iot-bridge: Unhandled Rejection

2019-10-03 03:25:47.310 ERROR  : azure-iot-bridge: { FetchError: invalid json response body at http://localhost:8080/things reason: Unexpected token F in JSON at position 0

2019-10-03 03:25:47.312 ERROR  : azure-iot-bridge:     at /home/pi/.mozilla-iot/addons/azure-iot-bridge/node_modules/node-fetch/lib/index.js:272:32

2019-10-03 03:25:47.314 ERROR  : azure-iot-bridge:     at <anonymous>

2019-10-03 03:25:47.315 ERROR  : azure-iot-bridge:     at process._tickCallback (internal/process/next_tick.js:189:7)

2019-10-03 03:25:47.317 ERROR  : azure-iot-bridge:   message: 'invalid json response body at http://localhost:8080/things reason: Unexpected token F in JSON at position 0',

2019-10-03 03:25:47.318 ERROR  : azure-iot-bridge:   type: 'invalid-json' }
`

**Comment by tim-hellhake** [comment]
Thanks for the hint, I'll look into it.

**Comment by tim-hellhake** [comment]
Are you sure the access token for the gateway is correct?
I can reproduce this behavior with an invalid access key.

**Comment by hurricaneMitch** [comment]
When I created the token I used the Python example to query the gateway remotely and I successfully received a response. Do I need to preface the token with "Bearer " in the configuration form? 
Fair warning, this is my first time using the gateway. I love it but I don't have much experience debugging. I would gladly debug on my gateway if you gave me some pointers on how to do it :)

I have experience with Azure services.

Thanks again for looking at this

**Comment by tim-hellhake** [comment]
> Do I need to preface the token with "Bearer " in the configuration form?

No, just the token.

> I love it but I don't have much experience debugging.

Don't worry, I'm about to improve the error messages for a better debugging experience.

**Comment by tim-hellhake** [comment]
0.1.2 is now available (https://github.com/mozilla-iot/addon-list/pull/492).
The error won't be gone but there should be more details in the message.

**Comment by hurricaneMitch** [comment]
Thanks @tim-hellhake! I'll be back in town later this week and will dig into the debug.

**Comment by tim-hellhake** [comment]
@hurricaneMitch
Any updates on this? 😄

**Comment by hurricaneMitch** [comment]
Looked this morning and the error is no longer showing. :)

**Comment by tim-hellhake** [comment]
@hurricaneMitch
I'm happy to hear that 🙂
